In [172]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# from mpl_toolkits.mplot3d import Axes3D

In [173]:
dataset = pd.read_csv('data/SaratogaHouses.csv')

In [174]:
X = dataset[['livingArea','landValue','rooms','centralAir']].values
y = dataset['price'].values
y

array([132500, 181115, 109000, ..., 194900, 125000, 111300], shape=(1728,))

In [175]:
pd.unique(dataset['centralAir'])

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [176]:
X[:,-1]

array(['No', 'No', 'No', ..., 'No', 'No', 'No'],
      shape=(1728,), dtype=object)

In [177]:
X

array([[906, 50000, 5, 'No'],
       [1953, 22300, 6, 'No'],
       [1944, 7300, 8, 'No'],
       ...,
       [1099, 20400, 3, 'No'],
       [1225, 16800, 7, 'No'],
       [1959, 26000, 6, 'No']], shape=(1728, 4), dtype=object)

In [178]:
from sklearn.preprocessing import LabelEncoder
#converting text to no

In [179]:
encoder = LabelEncoder()
X[:,-1] = encoder.fit_transform(X[:,-1])

In [180]:
X[:,-1]

array([0, 0, 0, ..., 0, 0, 0], shape=(1728,), dtype=object)

In [181]:
from sklearn.preprocessing import OneHotEncoder

In [182]:
fuel = dataset['fuel'].values

In [183]:
pd.unique(fuel)

<StringArray>
['electric', 'gas', 'oil']
Length: 3, dtype: str

In [184]:
fuel = encoder.fit_transform(fuel)

In [185]:
fuel[:20]

array([0, 1, 1, 1, 1, 1, 2, 2, 0, 1, 2, 1, 0, 1, 2, 1, 2, 1, 2, 2])

In [186]:
fuel = fuel.reshape(-1,1)
oneHot = OneHotEncoder()
fuel = oneHot.fit_transform(fuel)

In [187]:
fuel#matrix which is in the form of 0 & 1

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1728 stored elements and shape (1728, 3)>

In [188]:
fuel.toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]], shape=(1728, 3))

In [189]:
X

array([[906, 50000, 5, 0],
       [1953, 22300, 6, 0],
       [1944, 7300, 8, 0],
       ...,
       [1099, 20400, 3, 0],
       [1225, 16800, 7, 0],
       [1959, 26000, 6, 0]], shape=(1728, 4), dtype=object)

In [190]:
from sklearn.preprocessing import StandardScaler
#scale down the values

In [191]:
std = StandardScaler()
X = std.fit_transform(X)

In [192]:
y = y.reshape(-1,1)
y = std.fit_transform(y)

In [193]:
X.shape

(1728, 4)

In [194]:
B = np.zeros(X.shape[1])

In [195]:
B

array([0., 0., 0., 0.])

In [196]:
X0 = np.ones(X.shape[0])

In [197]:
X[:,3]

array([-0.76221375, -0.76221375, -0.76221375, ..., -0.76221375,
       -0.76221375, -0.76221375], shape=(1728,))

In [198]:
X = np.array([X0, X[:,0],X[:,1],X[:,2]])

In [199]:
X[:10]

array([[ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [-1.36985441,  0.31951971,  0.30499787, ..., -1.05844161,
        -0.85513584,  0.32920094],
       [ 0.44108417, -0.350095  , -0.77853137, ..., -0.4043636 ,
        -0.50718833, -0.24441402],
       [-0.88163155, -0.44981202,  0.41382706, ..., -1.74527063,
        -0.01799248, -0.44981202]], shape=(4, 1728))

In [200]:
X.shape

(4, 1728)

In [201]:
n = len(X)#length data
epochs = 5000 #no of cycler - Loop 
alpha = 0.0025 #learning rate 

In [202]:
X.shape

(4, 1728)

In [203]:
X = X.T

In [204]:
X.shape

(1728, 4)

In [205]:
X[:5]

array([[ 1.        , -1.36985441,  0.44108417, -0.88163155],
       [ 1.        ,  0.31951971, -0.350095  , -0.44981202],
       [ 1.        ,  0.30499787, -0.77853137,  0.41382706],
       [ 1.        ,  0.30499787, -0.45291972, -0.88163155],
       [ 1.        , -1.47634791, -0.5586007 , -1.74527063]])

In [206]:
def cost_function(X,y,B):
    return (np.sum((np.dot(X,B) - y) ** 2)) / (2 * n)

In [207]:
cost_function(X,y,B)

np.float64(373247.9999999999)

In [208]:
def gradient_descent(X,y,B,epochs,alpha):
    cost_history = [0] * epochs
    for i in range(epochs):
        y_pred = X.dot(B)
        loss = y_pred - y
        gradient = X.T.dot(loss) / n
        B = B - alpha * gradient
        cost_history[i] = cost_function(X,y,B)
        print("ch =>",cost_history[i])
        
    return cost_history, B

In [209]:
cost,b = gradient_descent(X,y.flatten(),B,epochs=10000,alpha=0.0001)

ch => 195.85202215165236
ch => 178.97984091107705
ch => 164.84512619817485
ch => 152.9982727406247
ch => 143.06376283486009
ch => 134.72794470864667
ch => 127.72882778273473
ch => 121.84756193949147
ch => 116.90132285387045
ch => 112.73737131965478
ch => 109.22809280874372
ch => 106.26685548334123
ch => 103.76455158391676
ch => 101.6467094111373
ch => 99.85108173517045
ch => 98.32563200829361
ch => 97.0268527338018
ch => 95.91836117925794
ch => 94.96972666874325
ch => 94.1554912421484
ch => 93.45435177617816
ch => 92.84847692741485
ch => 92.32293665432569
ch => 91.8652257459645
ch => 91.46486585009426
ch => 91.11307305254918
ch => 90.8024801963688
ch => 90.5269049132869
ch => 90.28115582975784
ch => 90.06087065345201
ch => 89.8623808846319
ch => 89.68259876391008
ch => 89.51892279188094
ch => 89.3691587606268
ch => 89.23145374184847
ch => 89.10424089782401
ch => 88.98619333330754
ch => 88.87618550031829
ch => 88.77326091312513
ch => 88.67660513560341
ch => 88.58552317421204
ch => 88.49

In [210]:
b
#gradient descents =>minimising the loss

array([2.59348099e-17, 5.48036921e-01, 3.41088765e-01, 2.71546080e-02])

In [179]:
B.shape, X.shape, y.shape

((4,), (1728, 4), (1728, 1))

In [180]:
y_pred = X.dot(B)

In [181]:
y_pred.shape

(1728,)

In [195]:
loss = y_pred - y.flatten()

In [196]:
loss.shape

(1728,)

In [197]:
grad = X.T.dot(loss) / n

In [198]:
grad

array([-4.97379915e-14, -3.07752581e+02, -2.51106709e+02, -2.29465493e+02])