In [1]:
# https://www.numpy.org/devdocs/user/quickstart.html
import numpy as np

# Ways to Create Array in Numpy

In [2]:
x1 = np.array([2,4,7,8,43,56,78,32,67])

In [3]:
print(x1)

[ 2  4  7  8 43 56 78 32 67]


In [4]:
x2 = np.array([i for i in range(1,100001) if i % 2 == 0])

In [7]:
len(x2)

50000

In [8]:
x2[:10]#starting 10

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
x3 = np.arange(2,10001,2)

In [10]:
len(x3)

5000

In [11]:
x3[:10]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
# will return array of 50 numbers starting from 1.0 to 10.0
# x4 = np.linspace(1,10)

# will return array of 20 numbers starting from 1.0 to 10.0
x4 = np.linspace(1,10, num=20,retstep=True)

In [18]:
x4

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 np.float64(0.47368421052631576))

In [20]:
np.random.rand(2,5,3)

array([[[0.86599153, 0.38745902, 0.43641311],
        [0.00158617, 0.28671294, 0.71006235],
        [0.3474943 , 0.47335836, 0.72692461],
        [0.48653466, 0.27843646, 0.76197655],
        [0.31689018, 0.91552632, 0.85944356]],

       [[0.41817682, 0.31482987, 0.46961838],
        [0.95000115, 0.34657384, 0.17990105],
        [0.15068592, 0.71456974, 0.99026784],
        [0.19829132, 0.98195773, 0.36519589],
        [0.84209043, 0.40847648, 0.57782075]]])

In [21]:
# will return 5 random numbers between 10 and 100
np.random.randint(10,100,5)

array([94, 82, 58, 70, 56])

In [24]:
np.random.seed(5)#fix the random state
np.random.randint(10,100,5)

array([88, 71, 26, 83, 18])

In [26]:
np.random.rand()

0.39673660521140586

In [31]:
np.random.seed(5)
np.random.rand()

0.22199317108973948

In [32]:
np.random.random([5,5])

array([[0.87073231, 0.20671916, 0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 , 0.18772123, 0.08074127],
       [0.7384403 , 0.44130922, 0.15830987, 0.87993703, 0.27408646],
       [0.41423502, 0.29607993, 0.62878791, 0.57983781, 0.5999292 ],
       [0.26581912, 0.28468588, 0.25358821, 0.32756395, 0.1441643 ]])

# Methods of Numpy

In [34]:
x = np.random.randint(10,1000,200)

In [35]:
x.max()

np.int64(997)

In [36]:
x.min()

np.int64(23)

In [37]:
x.mean()

np.float64(506.255)

In [49]:
x.shape

(200,)

In [53]:
x.ndim

1

In [51]:
x.argmax()

154

In [54]:
x[154]

995

In [55]:
x.argmin()

76

In [59]:
x.argsort()[:10]

array([ 76, 173,   5,  37, 175,  36,  82, 197,  74,  51], dtype=int64)

# Slicing Numpy Array

In [60]:
x = np.array([[4,5,3,2],[6,8,3,6],[8,8,4,7]])

In [61]:
x

array([[4, 5, 3, 2],
       [6, 8, 3, 6],
       [8, 8, 4, 7]])

In [38]:
x.ndim

1

In [39]:
x.shape

(200,)

In [64]:
# in 2d data by default slicing will be row wise
x[0:2]

array([[4, 5, 3, 2],
       [6, 8, 3, 6]])

In [65]:
x[0:2, 0:2]

array([[4, 5],
       [6, 8]])

In [66]:
x[:,0:2]

array([[4, 5],
       [6, 8],
       [8, 8]])

In [40]:
x = np.array([1,34,67,45,67,78,56,567,89])

In [43]:
x.argmin()#it will return the index of min value

np.int64(0)

In [44]:
x.argmax()

np.int64(7)

In [45]:
x.argsort()

array([0, 1, 3, 6, 2, 4, 5, 8, 7])